<?php


define("C_REST_CLIENT_ID", $_ENV["C_REST_CLIENT_ID"]);
define("C_REST_CLIENT_SECRET", $_ENV["C_REST_CLIENT_SECRET"]);

define("C_REST_WEB_HOOK_URL", $_ENV["C_REST_WEB_HOOK_URL"]);
define("C_REST_CURRENT_ENCODING", $_ENV["C_REST_CURRENT_ENCODING"]);
define("C_REST_IGNORE_SSL", $_ENV["C_REST_IGNORE_SSL"]);
define("C_REST_LOG_TYPE_DUMP", $_ENV["C_REST_LOG_TYPE_DUMP"]);
define("C_REST_BLOCK_LOG", $_ENV["C_REST_BLOCK_LOG"]);
define("C_REST_LOGS_DIR", ROOT .'/logs');